### ISSUE TITLE
PagesDueForReviewReport pagination doesn't work as expected

### ISSUE THREAD

**Issue by phalkunz** [silverstripe/silverstripe-contentreview#103]
After applying filters (e.g. Review date after), going to the next page by clicking Next button on the gridfield directs the user back the initial state of the report (`NextReviewDate` < today). It looks like gridfield doesn't take in the applied filters.
```text
silverstripe/contentreview            4.1.x-dev 188f77c 
silverstripe/framework                4.2.1 
```

**Comment by robbieaverill** [comment]
I think someone on the reports module has reported this too. Related: https://github.com/silverstripe/silverstripe-reports/issues/99 https://github.com/silverstripe/silverstripe-reports/pull/107#issuecomment-414856764

**Comment by phalkunz** [comment]
@robbieaverill We already got the path (https://github.com/silverstripe/silverstripe-reports/pull/107) for that issue so I think it's a different issue.

**Comment by robbieaverill** [comment]
Yeah it is. I think [this comment](https://github.com/silverstripe/silverstripe-reports/pull/107#issuecomment-414856764) is talking about the same issue you're having here.

**Comment by robbieaverill** [comment]
It looks `sourceRecords` is not given `$params` correctly when navigating between pages in the report

**Comment by phalkunz** [comment]
I see. The issue (https://github.com/silverstripe/silverstripe-reports/issues/99) is closed though. Should I move this to Report module instead?

**Comment by robbieaverill** [comment]
Fix at https://github.com/silverstripe/silverstripe-reports/pull/111

**Comment by phalkunz** [comment]
Thanks, @robbieaverill
