### ISSUE TITLE
"Error: Call to a member function OwnerGroups() on boolean" on Reports page

### ISSUE THREAD

**Issue by nathancox** [silverstripe/silverstripe-contentreview#108]
It looks like if you have a page with a `NextReviewDate` and `ContentReviewType` set to "Inherit" but the parent page has `ContentReviewType` set to "Disabled" the reports page throws the above error.

`PagesWithoutReviewScheduleReport::hasReviewSchedule()` assumes that if you have a `NextReviewDate` then `$record->getOptions()` will return a page but in the above situation it returns `false` instead.

**Comment by NightJar** [comment]
Hi @nathancox thanks for reporting. Can you please also provide information about what version you are experiencing this with, and what versions of the SS core modules you're using it with?

**Comment by nathancox** [comment]
Oh it's on CWP recipe 2.1.1 so contentreview 4.1.0 and SilverStripe framework/cms/reports 4.2.1

**Comment by robbieaverill** [comment]
Hi @nathancox, we've fixed this already with https://github.com/silverstripe/silverstripe-contentreview/pull/101 and https://github.com/silverstripe/silverstripe-contentreview/pull/102. It'll be available in the next CWP recipe release, or you can manually update to using the latest (unstable) contentreview version in your current project. Thanks for raising the issue =)
