### ISSUE TITLE
The behat test is broken with the latest version of CMS

### ISSUE THREAD

**Issue by dnsl48** [silverstripe/silverstripe-contentreview#120]
https://travis-ci.org/silverstripe/silverstripe-contentreview/jobs/609048407

```gherkin
When I click on "Home" in the tree
    And I click the "Settings" CMS tab
    Then I should see a "Content Review" button
```

**Content Review button not found**

**Comment by brynwhyman** [comment]
This has since been resolved in https://github.com/silverstripe/silverstripe-contentreview/pull/123. It was an issue with the test itself.
