### ISSUE TITLE
User in Group field does not receive a notification email

### ISSUE THREAD

**Issue by emteknetnz** [silverstripe/silverstripe-contentreview#125]
4.x-dev b6a6b59

Added the default "Content Author" to the
Site settings > Content Review > Group field

I had a user belonging to the "Content Author" group

Change a page content review date to in the past and published

- The user did not receive any notification
- I tried to manually create the queued job "Content Review Notification Job".  When I tried to manually run it had the status "Broken"

## Acceptance criteria
- [ ] When I assigned a user as a content reviewer, they will receive a notification email when content expire.
- [ ] When I assigned a group as content reviewer, all members of that group will receive a notification email when content expire.
- [ ] All content reviewers can interact with the content review modal whether they are directly define as a content review or added to a content reviewer group.
- [ ] No errors should be thrown if the member is missing an email or if there's no member in a group added as a reviewer group.

**Comment by brynwhyman** [comment]
It might be worth double checking the email of the user within the Content Author group. See: #129

**Comment by maxime-rainville** [comment]
This is still present in CWP 2.7. My user wasn't getting the email when it mas a member of the review group. When I explicitly made it a reviewer, than I started getting email notifications.

**Comment by emteknetnz** [comment]
Still present in CWP 2.8.0-rc1

**Comment by brynwhyman** [comment]
Bumping this to impact/critical. As I understand the featureset of this module, users rely on notifications to know if content is ready for review.

**Comment by GuySartorelli** [comment]
@maxime-rainville @emteknetnz I can't reproduce this.
Tested with Framework 4.10.4, CMS 4.10.1, contentreview 4.4.0

Are there specific modules I should be including in my install to check this? (e.g. you both mentioned CWP above)

**Comment by emteknetnz** [comment]
Yeah quite possibly it's specific to CWP.  This issue was reported while doing manual regressing testing on CCL hosting (used for CWP) with the CWP "recipe-kitchen-sink" installed, so included the CWP mail configuration.

**Comment by GuySartorelli** [comment]
Still can't reproduce this. I have tried it in SCPS with both a 4.x and a 4.10.0 install of kitchen sink - in both cases I received an email triggered for a user in a reviewer group.
I don't think this is a problem anymore, but it would be good for one of you two to confirm just in case there's something I've missed.

**Comment by emteknetnz** [comment]
If you can't replicate after following the replication steps, happy to close.  This issue is still in our manual regression suite so we can reopen if required
