### ISSUE TITLE
"Content Review button not found" - behat failure

### ISSUE THREAD

**Issue by emteknetnz** [silverstripe/silverstripe-contentreview#139]
https://travis-ci.com/github/silverstripe/silverstripe-contentreview/jobs/457112358

Issue is likely to do with a different module

Replicated locally using silverstripe/recipe-cms:
~4.5.0 issue replicated
~4.4.0 issue replicated
~4.3.0 works fine - issue not replicated

**Comment by brynwhyman** [comment]
@emteknetnz I couldn't recreate this in cwp/cwp-recipe-kitchen-sink (with CMS 4.6; silverstripe/contentreview 4.1.1)

![image](https://user-images.githubusercontent.com/15868440/102147539-c63d7180-3ecf-11eb-8696-580bcbfe9a44.png)


I think there's an issue with the test? There's a [PR that was merged a while ago](https://github.com/silverstripe/silverstripe-contentreview/pull/123/files) that tweaked the behat statements to a lowercase 'R' which seems to have reverted? Maybe that's the issue....

**Comment by emteknetnz** [comment]
Yup, lowercase r's in the linked PR was the culprit, will close this issue
