### ISSUE TITLE
When a page is under review, the button can't be clicked from the settings tab.

### ISSUE THREAD

**Issue by stojg** [silverstripe/silverstripe-contentreview#14]
To reproduce:

1) Make sure a page is 'reviewable' for a user.
2) Log in as that user and go to that page in the CMS.
3) Click on Settings tab
4) Click on the "Content Reviewed" button
5) Observe the fail.

**Comment by robbieaverill** [comment]
Can't reproduce any longer on SS 3.5.x or higher
