### ISSUE TITLE
Allow users with the CMS_ACCESS_LeftAndMain permission to be added

### ISSUE THREAD

**Issue by sabina-talipova** [silverstripe/silverstripe-contentreview#171]
Currently members could not be assigned if they had the 'All sections' permission CMS_ACCESS_LeftAndMain ticked instead of the 'Pages section' ticked CMS_ACCESS_CMSMain

### PR
- https://github.com/silverstripe/silverstripe-contentreview/pull/155
- https://github.com/silverstripe/silverstripe-contentreview/pull/154
- https://github.com/silverstripe/silverstripe-contentreview/pull/172

**Comment by GuySartorelli** [comment]
PRs all merged.
