### ISSUE TITLE
CMS 5 - User doesn't receive an email notification

### ISSUE THREAD

**Issue by sabina-talipova** [silverstripe/silverstripe-contentreview#186]
## Description
User doesn't receive an email notifying them of the page that is over due for a content review

## Regression test
- https://studio.cucumber.io/projects/301855/test-runs/748052/folder-snapshots/7887509/scenario-snapshots/27677686/test-snapshots/37762009

## Related issue
- https://github.com/silverstripe/silverstripe-contentreview/issues/125

**Comment by maxime-rainville** [comment]
We got an email a day later, so it looks like it worked.
