### ISSUE TITLE
Error as result of "Content Review Notification job": Address in mailbox given [beta4110] does not comply with RFC 2822.

### ISSUE THREAD

**Issue by sabina-talipova** [silverstripe/silverstripe-contentreview#188]
### Description
Regression tests have been executed on: SCPS PHP 8.1 Firefox GraphQL v4 Sink.
When user run "Content Review Notification job" in CMS "Jobs" section, job is failed and marked as "Broken". In Message Tab, user can see the following error:
```
[ERROR] Address in mailbox given [beta4110] does not comply with RFC 2822, 3.6.2. {"exception":"[object]
(Swift_RfcComplianceException(code: 0): Address in mailbox given [beta4110] does not comply with RFC 2822, 3.6.2. at
/sites/cmstest/releases/20230315055312/vendor/swiftmailer/swiftmailer/lib/classes/Swift/Mime/Headers/MailboxHeader.php:355)"} []
```
### Steps to reproduce
- I can log in to the CMS with permission to edit pages
- I am assigned as a content reviewer in the site settings
- T here is a page on the site with its Next review date set in the past
- The Content Review Notification job runs (Job is marked as broken and has ERROR message)

https://studio.cucumber.io/projects/301855/test-runs/758277/folder-snapshots/8007999/scenario-snapshots/28020711/test-snapshots/38195486

#### Related issue
- https://github.com/silverstripe/silverstripe-contentreview/issues/129

## PRs

**Comment by maxime-rainville** [comment]
This is not a regression form 4.13. But it is a bad behaviour. We should aim to provide early warnings if an invalid email is provided.

**Comment by sabina-talipova** [comment]
Close this issue as a duplicate
- https://github.com/silverstripe/silverstripe-contentreview/issues/129
