### ISSUE TITLE
ContentReviewEmails tasks not replaceable by Injector

### ISSUE THREAD

**Issue by michalkleiner** [silverstripe/silverstripe-contentreview#200]
The job creating the task uses `new ContentReviewEmails` instead of `ContentReviewEmails::create` so the task can't be replaced via Injector to customise its functionality.

**Comment by GuySartorelli** [comment]
This work falls under the general umbrella of https://github.com/silverstripe/silverstripe-framework/issues/10269

I'm going to close this issue for now - but if this instance of not using `::create()` is a genuine nuisance for you, and you're willing to make a PR to resolve this instance of it, feel free to reopen the issue with a link to the PR and I'll review it for you.

**Comment by michalkleiner** [comment]
This has already been done @GuySartorelli — https://github.com/silverstripe/silverstripe-contentreview/pull/201.

**Comment by GuySartorelli** [comment]
Oh, excellent. In that case I'll gladly review it 👍

**Comment by GuySartorelli** [comment]
No I won't, it was merged. That's what I get for commenting before I click the link.
