### ISSUE TITLE
BUG Saving review note does not work

### ISSUE THREAD

**Issue by tractorcow** [silverstripe/silverstripe-contentreview#25]
For whatever reason, pressing "save" on the dialog for reviewing a page does not save.

It appears that `ContentReviewCMSExtension::save_review` isn't invoked when the same button is pressed.

Tested with framework 3.2 and cwp 1.2.0 (pre-release) recipe.

**Comment by robbieaverill** [comment]
Needs revalidation

**Comment by robbieaverill** [comment]
Working in CWP 1.5+ and the SS4 compatible version
