### ISSUE TITLE
Pages uneditable - Error thrown

### ISSUE THREAD

**Issue by NightJar** [silverstripe/silverstripe-contentreview#55]
If a page has it's `ContentReviewType` set to `Disabled` AND there is a `NextReviewDate` which is in the past , a fatal PHP error is thrown and pages will not load in the CMS due to  `canBeReviewedBy` calling a method on a boolean value.

This stems from `getOptions` returning `false` if content review is `Disabled`.

**Comment by robbieaverill** [comment]
Fixed in #56
