### ISSUE TITLE
Typo

### ISSUE THREAD

**Issue by phptek** [silverstripe/silverstripe-contentreview#59]
Typo in `ContentReviewDefaultSettings`:

From:

> These content review settings will apply to all pages that does not have specific Content Review schedule.

To:

> These content review settings will apply to all pages that do not have a specific Content Review schedule.

**Comment by robbieaverill** [comment]
Cheers for pointing this out @phptek. Would you like to make a PR for it?

**Comment by phptek** [comment]
Yeah I pretty much always intend to. Tomorrow :-)
