### ISSUE TITLE
Fallback to SiteConfig doesn't work

### ISSUE THREAD

**Issue by robingram** [silverstripe/silverstripe-contentreview#68]
This seems to be extant in the 3.0 branch but I'm not sure if the changes for SS4 will have fixed it.

When sending emails if there are no settings on individual pages then the settings from SiteConfig won't be used. This is because https://github.com/silverstripe/silverstripe-contentreview/blob/3.0/code/extensions/SiteTreeContentReview.php#L211 returns a `SiteConfig` object whereas https://github.com/silverstripe/silverstripe-contentreview/blob/3.0/code/extensions/SiteTreeContentReview.php#L457 is looking for the `SiteTreeContentReview` extension, which isn't applied to `SiteConfig`. As a result `canBeReviewedBy` returns false and no email will be sent for the page.

**Comment by robbieaverill** [comment]
@robingram would you be keen to test out the changes at #69 to see if it fixes this issue for you?

**Comment by robingram** [comment]
Thanks @robbieaverill. Tested by removing all member and group associations with `sitetreecontentreview` and adding a single group to the SiteConfig. Review emails were sent to the group as expected.

**Comment by robbieaverill** [comment]
Fixed in #69 and released as 3.0.7
