### ISSUE TITLE
Review SS4 upgrade

### ISSUE THREAD

**Issue by rupachup** [silverstripe/silverstripe-contentreview#73]
## Acceptance Criteria

- [ ] Works on SS4
- [ ] Beta 2 tag released

## Sub Tasks

- [x] #74
- [x] https://github.com/silverstripe/silverstripe-contentreview/issues/72

**Comment by robbieaverill** [comment]
I've put a PR up to fix #72 - hopefully this is enough to continue with this task @raissanorth?

**Comment by raissanorth** [comment]
Thanks heaps!

**Comment by raissanorth** [comment]
Tested. Updates made in PRs #78 and #80 and merged.
