### ISSUE TITLE
Tests are broken!

### ISSUE THREAD

**Issue by raissanorth** [silverstripe/silverstripe-contentreview#77]
Dodgy date assertions in the unit tests are now breaking stuff

**Comment by robbieaverill** [comment]
@raissanorth you said they were passing again locally, I've re-run the latest master build in Travis to double check: https://travis-ci.org/silverstripe/silverstripe-contentreview/builds/320000154

If this passes we can close this issue

**Comment by robbieaverill** [comment]
#219 passed
 Ran for 3 min 29 sec
 Total time 12 min 25 sec
 less than a minute ago
