### ISSUE TITLE
Remove "Add Page" button from content review tab in Member's profile

### ISSUE THREAD

**Issue by robbieaverill** [silverstripe/silverstripe-contentreview#81]
When viewing your profile in the CMS and heading to Site Tree Content Review, there's an "Add Page" button which lets you create a new page.

This is a bizarre UX flow, so let's remove it.

The tab presumably exists to list reviews on pages that the user has entered in the past, so keeping it provides some value overall.

* remove add new and link existing functionality

**Comment by clarkepaul** [comment]
Just out of interest it might be good to get a screenshot as I'm not familiar with the UI of the content review module (if you have it open that is).

**Comment by robbieaverill** [comment]
![image](https://user-images.githubusercontent.com/5170590/37747147-9ecf4412-2de2-11e8-899d-33b2c757ea7a.png)

@clarkepaul

**Comment by clarkepaul** [comment]
Thanks :), super confusing UI but I can see that those actions/fields don't make sense at all.

**Comment by robbieaverill** [comment]
PR to remove the GridField completely at #82
