### ISSUE TITLE
automatically update next review date

### ISSUE THREAD

**Issue by torleif** [silverstripe/silverstripe-contentreview#94]
if you review a page via the review log, you have to manually set date you want to next review it.

this should update according to the Review frequency time. otherwise, what's the point in the review frequency time?

**Comment by robbieaverill** [comment]
Sounds like a bug to me. Thanks for reporting!

**Comment by NightJar** [comment]
I had this come up from another source today as well. Seems like there's some weird disconnect between code and user interface after taking a quick squiz.

The next review date is advanced upon review submission:
https://github.com/silverstripe/silverstripe-contentreview/blob/7f985ee5c87f62c2b6d81f39129c377a1a4fbe90/src/Forms/ReviewContentHandler.php#L99

which is routed and provided for via the [CMS Extension](https://github.com/silverstripe/silverstripe-contentreview/blob/4.1.0/src/Extensions/ContentReviewCMSExtension.php)

However I could not see any UI component for gaining access to that form. I saw from screenshots in the userhelp that one can add Review Log items, but that is not the same thing (and does not trigger the next review date advance).
Although I also could not see the code that adds the 'add a review log' button.

**Comment by robbieaverill** [comment]
I've just tested this on SilverStripe 4.3.x-dev with contentreview 4.1.x-dev and I can't reproduce it. Steps I took:

* Open Contact Us page and go to Settings tab
* Select Content Review tab and choose "Custom settings" from "Options"
* Set "Administrators" in "Groups", "Next review date" to a date before now, and "Review frequency" to 1 week. Save the page
* Change the content and save the page
* Click on orange bell icon in the CMS actions toolbar and enter a review
* Go back to the Content Review settings tab and check that the "Next review date" is one week from now

Feel free to reopen if you can provide more steps to reproduce!
